export const TOOLS = [
  { id: 1, title: "Java" },
  { id: 2, title: "Spring" },
  { id: 3, title: "Thymeleaf" },
  { id: 4, title: "Agile, Scrum Framework" },
  { id: 5, title: "Monolithic, Microservice" },
  { id: 6, title: "Gradle & Maven" },
  { id: 7, title: "Junit5 & Mockito" },
  { id: 8, title: "Test Driven Development" },
  { id: 9, title: "Behaviour Driven Development" },
  { id: 10, title: "Unit Testing" },
  { id: 11, title: "Integration Testing" },
  { id: 12, title: "SonarLint / Sonarqube" },
  { id: 13, title: "Jenkins" },
  { id: 14, title: "Gitlab CI/CD" },
  { id: 15, title: "Swagger API" },
  { id: 16, title: "Docker" },
  { id: 17, title: "React.js" },
  { id: 18, title: "Next.js" },
  { id: 19, title: "Node.js" },
  { id: 20, title: "Cypress" },
  { id: 21, title: "Jest" },
  { id: 22, title: "End-to-end Testing" },
  { id: 23, title: "Python" },
  { id: 24, title: "Flask" },
  { id: 25, title: "MySQL, MariaDB, SQLite" },
  { id: 26, title: "Heroku, LoadMill, LogDNA" },
  { id: 27, title: "Android Development" },
  { id: 28, title: "Tailwind CSS" },
  { id: 29, title: "Bootstrap CSS" },
  { id: 30, title: "Material UI" },
  { id: 31, title: "Vagrant" },
  { id: 32, title: "RedHat Openshift" },
  { id: 33, title: "Terraform" },
  { id: 34, title: "NginX" },
];
